### ISSUE TITLE
Error when saving object with AWS region specified

### ISSUE THREAD

**Issue by ramhiser** [cloudyr/aws.s3#106]
The error message is `Cannot detect correct region from bucket` and is thrown by `aws.s3:::get_region.default`. The error began occurring with a recent commit (unsure which one).

Reproducible Steps (assuming AWS credentials are loaded and the bucket and file exist):

```r
save_object("folder/foo.xyz", file = "foo.xyz", bucket = "my_bucket", region = "us-west-2")
```

Stepping through the above code yields 2 calls to `s3HTTP`. The first call is by `save_object`, where region is set to `us-west-2`. However, within the `s3HTTP`, this line appears:

```r
bucketregion <- get_region(bucket)
```

The call to `get_region` calls `aws.s3:::get_location`, which then makes the second call to `s3HTTP`. The second call to `s3HTTP` overwrites the AWS region.

Finally, within `aws.s3:::get_region.default`, the variable named `out` contains:

```r
List of 5
 $ Code     : chr "AuthorizationHeaderMalformed"
 $ Message  : chr "The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'"
 $ Region   : chr "us-west-2"
...
```

**Comment by leeper** [comment]
This was probably introduced by https://github.com/cloudyr/aws.s3/commit/3b232b36b73cf62963ff35c316ff2e9ea3339a25. I think I've fixed this in https://github.com/cloudyr/aws.s3/commit/fc7a42f6bba20e45e2becc7954d2739cdfab4a50. Want to try reinstalling and letting me know if it works now?

**Comment by ramhiser** [comment]
That didn't appear to fix it. Here's the error now:

```r
exiting from: s3HTTP(verb = "GET", bucket = bucket, query = list(location = ""), 
    check_region = FALSE, ...)
Error in get_region.default(bucket, key = key, secret = secret, session_token = session_token) : 
  Cannot detect correct region from bucket
In addition: Warning message:
In parse_aws_s3_response(r, Sig) : Bad Request (HTTP 400).
```

I'm debugging right now to see if I can identify where it goes wrong.

**Comment by leeper** [comment]
Can you give me `sessionInfo()` as well?

**Comment by ramhiser** [comment]
The second call to `s3HTTP` is now skipping the region check but then sets the region to default value of `us-east-1` from `Sys.getenv("AWS_DEFAULT_REGION", "us-east-1")`.

Again within the second call to `s3HTTP`, the incorrect region is being passed to `aws.signature::signature_v4_auth`, from which incorrect headers in `H` are generated.

The subsequent line yields a 400 response: `r <- GET(url, H, query = query, ...)`. The error then occurs in `get_region.default`.

```r
> out <- get_location(bucket = x, ...)
> class(out)
[1] "aws_error"
> out
AWS API Error Encountered. Details below:
List of 5
 $ Code     : chr "AuthorizationHeaderMalformed"
 $ Message  : chr "The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'"
 $ Region   : chr "us-west-2"
...
```

**Comment by ramhiser** [comment]
Sure. Here it is:

```r
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin16.1.0 (64-bit)
Running under: macOS Sierra 10.12.2

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.1.38   pumpjack_0.1.0  devtools_1.12.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9         tidyr_0.6.0         assertthat_0.1      digest_0.6.11       dplyr_0.5.0        
 [6] withr_1.0.2         aws.signature_0.2.6 R6_2.2.0            DBI_0.5-1           magrittr_1.5       
[11] git2r_0.17.0        httr_1.2.1          curl_2.3            rstudioapi_0.6      xml2_1.1.0.9000    
[16] tools_3.3.2         readr_1.0.0         base64enc_0.1-3     memoise_1.0.0       tibble_1.2    
```

**Comment by leeper** [comment]
This is puzzling because I can't seem to reproduce it on my machine.

**Comment by ramhiser** [comment]
Hmm. Puzzling, indeed. Anything I can do to help reproduce?

**Comment by leeper** [comment]
Do you have a default region set in your environment variables?

**Comment by ramhiser** [comment]
No.

```
> Sys.getenv("AWS_DEFAULT_REGION")
[1] ""
```

**Comment by leeper** [comment]
Okay. I need to step away from this for a bit, but will try to get back to it tomorrow.

**Comment by GiulianoFormato** [comment]
Hi, I am having the same issue. It is not happening on my machine. But when I run this code by a shiny server I got the same error:
```{r}
library(aws.s3)

### file env.txt contains the AWS info that I use later in the get_bucket function
AWS <- readLines("env.txt")
AWS <- do.call(rbind, strsplit(sub("=", "\n", AWS), "\n"))
AWS <- as.list(structure(AWS[,2], names = AWS[,1]))

# loading S3 bucket
aws.bucket.info <- get_bucket(bucket = AWS$AWS_BUCKET_NAME, region = AWS$AWS_DEFAULT_REGION, key = AWS$AWS_ACCESS_KEY_ID, secret = AWS$AWS_SECRET_ACCESS_KEY)
```

Hope this helps!

**Comment by GiulianoFormato** [comment]
Acatually, the issue with shiny server could be due to the fact that shiny server filters many environment varaibles (such as AWS variables). That was the reason why I had to specify them using the "env.txt" file and it was working that way, until the recent commits.
I am trying to debug the code run by shiny server (not easy :) ).
Let me know if you want more details about it.

**Comment by leeper** [comment]
@GiulianoFormato Want to migrate that to a new issue since it sounds like it could be distinct from this one and possibly Shiny-specific?

**Comment by GiulianoFormato** [comment]
Hi, it is true that in my case the issue is happening with shiny server, but I suppose (probably I am wrong :) ) this is just a "working environment" that make the same error happen.

Passing to the function get bucket "check_region=F", I was able to avoid the issue.
Doing the same with s3readRDS, the error is still there.

Thanks for your answer!

**Comment by GiulianoFormato** [comment]
@leeper I confirm you that the same issue happens also on my unix machine (Ubuntu 15.10) where the env variables used by the package are not defined. 
To make the commands `get_bucket` and `s3readRDS` work, I have to either define the env variables on my machine or specify the input variable used by `s3HTTP` as follows:
```{ r } 
check_region = FALSE
```

**Comment by PauloCirino** [comment]
I think I have the same problem.

Assuming I first set the AWS enviroment variable via :
`## Sets S3 Environment and BucketName
Sys.setenv(
    "AWS_ACCESS_KEY_ID" = "XYZ",
    "AWS_SECRET_ACCESS_KEY" = "ABCDEFGH1234567890",
    "AWS_DEFAULT_REGION" = "us-west-2"
)`

Whenever I try to use the function `uploadFileToS3()`, R throws the following error : 
` Error in get_region.default(bucket, key = key, secret = secret, session_token = session_token) : 
  Cannot detect correct region from bucket 
6. stop("Cannot detect correct region from bucket") 
5. get_region.default(bucket, key = key, secret = secret, session_token = session_token) 
4. get_region(bucket, key = key, secret = secret, session_token = session_token) 
3. s3HTTP(verb = "PUT", bucket = bucket, path = paste0("/", object), 
    headers = c(headers, list(`Content-Length` = ifelse(is.character(file) && 
        file.exists(file), file.size(file), length(file)))), 
    request_body = file, ...) 
2. put_object(file = outputFileName, object = outputFileName, bucket = buketName) 
1. uploadFileToS3(outputFileName = "1047foo.csv") 
In addition: Warning message:
In parse_aws_s3_response(r, Sig) : Forbidden (HTTP 403).`

And here is where it get's interesting, I have the same exact code running both on my macbook and on a private server.
The one on my computer works fine, and the one on the server worked fine until last week but for some unknown reason stoped working.


The `sessionInfo()` on my macbook : 
`R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.3

locale:
[1] pt_BR.UTF-8/pt_BR.UTF-8/pt_BR.UTF-8/C/pt_BR.UTF-8/pt_BR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.1.34

loaded via a namespace (and not attached):
 [1] httr_1.2.1          plumber_0.3.1       R6_2.2.0            rsconnect_0.6       tools_3.3.2        
 [6] base64enc_0.1-3     curl_2.3            aws.signature_0.2.6 Rcpp_0.12.9.3       xml2_1.1.0         
[11] stringi_1.1.2       digest_0.6.11       httpuv_1.3.3       
`

The `sessionInfo()` on the server : 
`
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.s3_0.1.38

loaded via a namespace (and not attached):
[1] httr_1.2.1          R6_2.2.0            tools_3.3.2         base64enc_0.1-3    
[5] curl_2.3            Rcpp_0.12.8         aws.signature_0.2.7 xml2_1.1.1         
[9] digest_0.6.10      
`

**Comment by leeper** [comment]
@PauloCirino what is the `uploadFileToS3()` function?

**Comment by PauloCirino** [comment]
Sorry I wrote down the wrong function here on github, this function is wrapper around the `aws.s3::put_object`, where the error is actually coming from.

**Comment by leeper** [comment]
Can everyone on the thread check whether this issue is still occurring with most recent version on GitHub? @PauloCirino @GiulianoFormato @ramhiser

**Comment by GiulianoFormato** [comment]
Hi @leeper , I just tested it and the issue is not occurring with the latest version.

**Comment by GiulianoFormato** [comment]
Hi, while testing I found this issue with `bucketlist()` which is actually not related with #106

![image](https://cloud.githubusercontent.com/assets/17035500/25478990/9b9fc566-2b43-11e7-8c33-d69f4a88185b.png)

Hope this helps.
Giuliano

**Comment by leeper** [comment]
@GiulianoFormato Okay, thanks for that. I'll investigate.

**Comment by gugaiz** [comment]
Hi, this issue is still happening to me
