### ISSUE TITLE
Restrictions on put object size?

### ISSUE THREAD

**Issue by cboettig** [cloudyr/aws.s3#22]
Getting this somewhat cryptic error from calls to `objectput` now, looks like the object I'm trying to put may be too large.  Any idea where this is documented in the AWS S3 docs?  Maybe a post method would work still?

```
Error in curl::handle_setopt(handle, .list = req$options) : 
  Option postfieldsize_large (30120) not supported.
Calls: s3copy ... <Anonymous> -> request_perform -> <Anonymous> -> .Call
```

**Comment by leeper** [comment]
This is an httr problem. It was just fixed here: https://github.com/hadley/httr/commit/c893eda50413835ce451ddb5c1f01d5a44f766ae

**Comment by cboettig** [comment]
Hmm, I believe I have those versions of `curl` and `httr` but still get that error.  You can see the versions I'm using on rocker/ropensci:dev docker image, or just in the Circle logs here: 
https://circleci.com/gh/cboettig/drat/168 (last block shows the error message, just before that block I print the package versions:

```
packageVersion("curl"); packageVersion("httr")
[1] ‘0.9.9000’
[1] ‘1.0.0.9000’
> 
```

**Comment by leeper** [comment]
I don't think Hadley bumped the httr version number after that change, so I guess it depends on your exact setup. Is the container rebuilt regularly or is it possible it's using a slightly older (but same versioned) httr?

**Comment by cboettig** [comment]
no luck.  `httr:::body_config` shows it has the parameter as `postfieldsize_large` instead of `postfieldsize`: 

```r
 httr:::body_config
function (body = NULL, encode = "form", type = NULL) 
{
... # stuff omitted 
        }, postfieldsize_large = size), content_type(body$type)))
```

The error message comes from @jeroenooms ' `curl` functions, not `httr` directly, so it seems from the message `httr` must be passing something called `postfieldsize_large` I would think...

**Comment by jeroenooms** [comment]
Can you try to reinstall `curl` from CRAN?

**Comment by cboettig** [comment]
@jeroenooms bingo, thanks.  Running with CRAN versions of `curl` and `httr` this works fine.

**Comment by cboettig** [comment]
Okay, I'll assume this will be worked out in the new curl/httr and will stick with using CRAN versions for now, sorry.

**Comment by jeroenooms** [comment]
No it was my fault. I accidentally had bumped the curl version to `0.9.9000` at some point, which should have been `0.9.0.9000`. It seems you had installed it exactly in the brief time that this version was on github, so you were not getting the `0.9.1` update.

**Comment by cboettig** [comment]
@jeroenooms ha, thanks, you've illustrated a weakness in our little drat system.  It captures nightly builds from GitHub, so it had captured the higher version numbered older sources.  Will have to delete the `0.9.9` manually from the drat repo & PACKAGES lists...

**Comment by leeper** [comment]
Thanks, @jeroenooms!

@cboettig Maybe file that as an issue on drat? Might be worth having a check during `insertPackage` to confirm you're not inserting an older version.
